name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ContainerFile --tag miah0x41/ccd2cue:0.5-$(date +%s)
